<<<<<<< HEAD
# Example of finally block exception in python...

try:
    num = 10
    denom = 0
    result = num/denom
    print(result)
except:
    print("Denominator cannot be 0")
finally:
=======
# Example of finally block exception in python...

try:
    num = 10
    denom = 0
    result = num/denom
    print(result)
except:
    print("Denominator cannot be 0")
finally:
>>>>>>> 2f455337bbd98e35313ab1d5f2b408fa185fca51
    print("This is finally block")